# Generated by Django 3.0.5 on 2020-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agents_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='image',
            field=models.ImageField(upload_to='agents/%Y/%m/%d'),
        ),
    ]
