# Generated by Django 3.0.5 on 2020-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
