# Generated by Django 3.0.5 on 2020-04-04 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200404_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/'),
            preserve_default=False,
        ),
    ]
