# Generated by Django 3.0.5 on 2020-04-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Propertie'},
        ),
    ]
