# Generated by Django 3.0.5 on 2020-04-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
