# Generated by Django 3.0.5 on 2020-04-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10),
        ),
    ]
